name: floor
description: >
  A supportive SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 0.9.0
homepage: https://github.com/vitusortner/floor
author: Vitus Ortner <vitusortner.dev@gmail.com>

environment:
  sdk: '>=2.3.0-dev <3.0.0'

dependencies:
  path: ^1.6.2
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: master
  floor_annotation:
    git:
      url: https://github.com/zzd258147/floor.git
      path: floor_annotation
      ref: sqlcipher
  meta: ^1.1.6
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.0
  flutter_test:
    sdk: flutter
